import { chromium } from 'playwright';
import fs from 'node:fs';
const out = '/tmp/claude-0/-home-user-fulltimedigi-app/dc64386e-3636-55db-bf63-338cab5c6ded/scratchpad';
const browser = await chromium.launch({ executablePath: process.env.CHROME_PATH });
const page = await browser.newPage({ viewport: { width: 1400, height: 1000 } });
page.on('pageerror', (e) => console.log('pageerror', e.message));
await page.goto('http://localhost:8090/index.html');
await page.waitForFunction(() => COMPILED && !BUSY, null, { timeout: 90000 });
const grab = async (name, t) => { const d = await page.evaluate(async (t) => { window.doodle.seek(t); const c = document.createElement('canvas'); c.width = 960; c.height = 540; window.doodle.paint(c.getContext('2d'), 0.5, HAND_IMG); return c.toDataURL('image/png'); }, t); fs.writeFileSync(`${out}/${name}.png`, Buffer.from(d.split(',')[1], 'base64')); };
const tPop = await page.evaluate(() => { const s = COMPILED.scenes[COMPILED.scenes.length - 1]; const e = s.elements.find((x) => x.kind === 'text'); return e.start + e.draw * 0.45; });
await grab('pop-mid', tPop);
const tHook = await page.evaluate(() => { const e = COMPILED.scenes[0].elements[1]; return e.start + e.draw * 0.5; });
await grab('hook-mid', tHook);
await page.evaluate(() => { SCRIPT.board = 'glass'; changed(); });
await page.waitForFunction(() => COMPILED && !BUSY, null, { timeout: 90000 });
await grab('glass', await page.evaluate(() => COMPILED.scenes[2].start + 4));
await page.evaluate(() => { SCRIPT.board = 'chalk'; changed(); });
await page.waitForFunction(() => COMPILED && !BUSY, null, { timeout: 90000 });
await grab('chalk', await page.evaluate(() => COMPILED.scenes[0].start + 5));
await page.evaluate(() => toggleEditor(0, 1)); await page.waitForTimeout(100);
await page.locator('#scenesCard .scene').first().screenshot({ path: `${out}/editor2.png` });
await page.evaluate(() => { SCRIPT.board = 'paper'; changed(); });
await browser.close();
