import { chromium } from 'playwright';
import fs from 'node:fs';
const browser = await chromium.launch({ executablePath: process.env.CHROME_PATH });
const page = await (await browser.newContext({ viewport: { width: 1240, height: 900 } })).newPage();
const errors = []; page.on('pageerror', (e) => errors.push(e.message)); const dialogs = []; page.on('dialog', (d) => { dialogs.push(d.message()); d.message().includes('ميزانية') ? d.dismiss() : d.accept(); });
const png = fs.readFileSync('examples/art/shop-owner.png').toString('base64'); const clip = fs.readFileSync('scripts/.dbg/fixtures/clip.webm');
const SCRIPT = { creator: 'c', setting: 's', clips: [{ role: 'hook', say: 'x', action: 'a', camera: 'c' }, { role: 'cta', say: 'y', action: 'a', camera: 'c' }], caption: 'c', hashtags: ['#x'] };
await page.route('https://generativelanguage.googleapis.com/**', async (route) => { const u = route.request().url(); const reply = (st, o) => route.fulfill({ status: st, contentType: 'application/json', body: JSON.stringify(o) });
  if (u.includes('predictLongRunning')) return reply(200, { name: 'operations/op1' });
  if (u.includes('operations/op1')) return reply(200, { done: true, response: { generateVideoResponse: { generatedSamples: [{ video: { uri: 'https://generativelanguage.googleapis.com/v1beta/files/x:download' } }] } } });
  if (u.includes(':download')) return route.fulfill({ status: 200, contentType: 'video/webm', body: clip });
  const body = JSON.parse(route.request().postData()); const sys = body.systemInstruction?.parts?.[0]?.text || '';
  if (/phone_visible/.test(sys)) return reply(200, { candidates: [{ content: { parts: [{ text: '{"phone_visible":false}' }] } }] });
  if ((body.generationConfig?.responseModalities || []).includes('IMAGE')) return reply(200, { candidates: [{ content: { parts: [{ inlineData: { mimeType: 'image/png', data: png } }] } }] });
  return reply(200, { candidates: [{ content: { parts: [{ text: JSON.stringify(SCRIPT) }] } }] }); });
await page.goto('http://localhost:8090/ugc.html'); await page.evaluate(() => { localStorage.setItem('gemini_key', 'x'); localStorage.setItem('budget_day', '0.5'); localStorage.removeItem('spend_log'); }); await page.reload();
await page.fill('#brief', 'x'); await page.evaluate(() => writeScript()); await page.waitForFunction(() => document.querySelectorAll('#clipsEd .clip').length > 0);
await page.evaluate(() => shootOne(0)); await page.waitForTimeout(3000);
console.log('budget dialog shown:', dialogs.some((m) => m.includes('ميزانية')), '| clip blocked:', await page.evaluate(() => Object.keys(CLIPS).length === 0), '| msg:', (await page.$eval('#msg2', (e) => e.textContent)).slice(0, 50));
await page.evaluate(() => { localStorage.setItem('budget_day', '50'); }); await page.evaluate(() => shootOne(0)); await page.waitForFunction(() => document.querySelector('#clips video'), null, { timeout: 60000 });
console.log('chip:', await page.$eval('#spendChip', (e) => e.textContent.trim()), '| log:', await page.evaluate(() => Suite.spend.log().map((x) => x.label + ' ' + x.usd).join(', ')));
console.log('errors', errors); await browser.close();
